---
- block:
    - name: Gather facts to gather current image file
      ios_facts:
        gather_subset:
          - min
          - hardware
      register: output

    - name: Show installed boot image file
      debug: msg="{{ ansible_net_image }}"
      when: output is defined

    - name: Now Upgrading The Switch
      debug: msg="Upgrading Switch {{inventory_hostname}}"

    - name: Device primary volume name
      ios_command:
        commands:
          - "dir"
      register: dir_output

    - block:
        - name: Determine if primary volume name is bootflash
          set_fact: device_primary_flash="bootflash"
          when: dir_output['stdout'][0][:40].find(' bootflash:') != -1

        - name: Determine if primary volume name is flash
          set_fact: device_primary_flash="flash"
          when: dir_output['stdout'][0][:40].find(' flash:') != -1

        - name: Determine if primary volume name is flash-1
          set_fact: device_primary_flash="flash-1"
          when: dir_output['stdout'][0][:40].find(' flash-1:') != -1

    - name: debug primary flash name
      debug: msg="{{ device_primary_flash }}"
      poll: 0
      when: device_primary_flash is defined

    - name: Run upgrade commands
      ios_command:
        commands:
          - "conf t"
          - "no boot system"
          - "boot system {{ device_primary_flash }}:{{ image.ios.os_dst_filename }}"
          - "boot system {{ device_primary_flash }}:{{ ansible_net_image.split(':')[-1] | replace('/', '') }}"
      vars:
        ansible_command_timeout: 600
      when: device_primary_flash is defined

    - name: Save running config before exiting
      ios_config:
        save_when: always

    - name: Reload the device
      cli_command:
        command: "reload"
        check_all: True
        prompt:
          - "Proceed with reload?"
        answer:
          - "\r"
